/*
 * SPDX-FileCopyrightText: Copyright 2011 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-wisun
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/*!
 * \defgroup wisun Wi-SUN
 */

#ifndef INCLUDED_WISUN_API_H
#define INCLUDED_WISUN_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_wisun_EXPORTS
#define WISUN_API __GR_ATTR_EXPORT
#else
#define WISUN_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_WISUN_API_H */
