/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clipping_detector_c.h)                                     */
/* BINDTOOL_HEADER_FILE_HASH(a00e4be6253c25d6476c969e6deef15b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/clipping_detector_c.h>
// pydoc.h is automatically generated in the build directory
#include <clipping_detector_c_pydoc.h>

void bind_clipping_detector_c(py::module& m)
{

    using clipping_detector_c = ::gr::wisun::clipping_detector_c;


    py::class_<clipping_detector_c,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<clipping_detector_c>>(
        m, "clipping_detector_c", D(clipping_detector_c))

        .def(py::init(&clipping_detector_c::make),
             py::arg("threshold") = 0.99f,
             py::arg("report_period") = 8000000,
             D(clipping_detector_c, make))


        .def("samples", &clipping_detector_c::samples, D(clipping_detector_c, samples))


        .def("clipped_samples",
             &clipping_detector_c::clipped_samples,
             D(clipping_detector_c, clipped_samples))

        ;
}
