/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(correlate_sync_word_bb.h) */
/* BINDTOOL_HEADER_FILE_HASH(43fe179d87e6cf3c277db392c3fc91b1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/correlate_sync_word_bb.h>
// pydoc.h is automatically generated in the build directory
#include <correlate_sync_word_bb_pydoc.h>

void bind_correlate_sync_word_bb(py::module& m)
{

    using correlate_sync_word_bb = ::gr::wisun::correlate_sync_word_bb;


    py::class_<correlate_sync_word_bb,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<correlate_sync_word_bb>>(
        m, "correlate_sync_word_bb", D(correlate_sync_word_bb))

        .def(py::init(&correlate_sync_word_bb::make),
             py::arg("sfd"),
             D(correlate_sync_word_bb, make))


        ;
}
