/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(data_whitening_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0a3d95fb0739b8f5d63a388678e65398)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/data_whitening_bb.h>
// pydoc.h is automatically generated in the build directory
#include <data_whitening_bb_pydoc.h>

void bind_data_whitening_bb(py::module& m)
{

    using data_whitening_bb = ::gr::wisun::data_whitening_bb;


    py::class_<data_whitening_bb,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<data_whitening_bb>>(
        m, "data_whitening_bb", D(data_whitening_bb))

        .def(py::init(&data_whitening_bb::make),
             py::arg("packet_tag"),
             py::arg("header_bits"),
             D(data_whitening_bb, make))


        ;
}
