/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gated_power_squelch_relative_cc.h) */
/* BINDTOOL_HEADER_FILE_HASH(bdfbf4275957579d5179edb38a8c4d76)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/gated_power_squelch_relative_cc.h>
// pydoc.h is automatically generated in the build directory
#include <gated_power_squelch_relative_cc_pydoc.h>

void bind_gated_power_squelch_relative_cc(py::module& m)
{

    using gated_power_squelch_relative_cc = ::gr::wisun::gated_power_squelch_relative_cc;


    py::class_<gated_power_squelch_relative_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<gated_power_squelch_relative_cc>>(
        m, "gated_power_squelch_relative_cc", D(gated_power_squelch_relative_cc))

        .def(py::init(&gated_power_squelch_relative_cc::make),
             py::arg("relative_threshold"),
             py::arg("alpha"),
             py::arg("trailing_samples"),
             D(gated_power_squelch_relative_cc, make))


        .def("set_channel",
             &gated_power_squelch_relative_cc::set_channel,
             py::arg("channel"),
             D(gated_power_squelch_relative_cc, set_channel))

        ;
}
