/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_add_pcapng_header.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(01413b9be720a4dd8daa168b5b58f480)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/pdu_add_pcapng_header.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_add_pcapng_header_pydoc.h>

void bind_pdu_add_pcapng_header(py::module& m)
{

    using pdu_add_pcapng_header    = gr::wisun::pdu_add_pcapng_header;


    py::class_<pdu_add_pcapng_header, gr::block, gr::basic_block,
        std::shared_ptr<pdu_add_pcapng_header>>(m, "pdu_add_pcapng_header", D(pdu_add_pcapng_header))

        .def(py::init(&pdu_add_pcapng_header::make),
           D(pdu_add_pcapng_header,make)
        )
        



        ;




}








