/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_duplicate_monitor.h)                                   */
/* BINDTOOL_HEADER_FILE_HASH(9a16aab0f2512475daabdacf9e6f9793)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/pdu_duplicate_monitor.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_duplicate_monitor_pydoc.h>

void bind_pdu_duplicate_monitor(py::module& m)
{

    using pdu_duplicate_monitor = ::gr::wisun::pdu_duplicate_monitor;


    py::class_<pdu_duplicate_monitor,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_duplicate_monitor>>(
        m, "pdu_duplicate_monitor", D(pdu_duplicate_monitor))

        .def(py::init(&pdu_duplicate_monitor::make),
             py::arg("window_ms") = 100,
             py::arg("history") = 16,
             D(pdu_duplicate_monitor, make))


        .def("duplicates",
             &pdu_duplicate_monitor::duplicates,
             D(pdu_duplicate_monitor, duplicates))

        ;
}
