/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_fec_decode.h)                                          */
/* BINDTOOL_HEADER_FILE_HASH(52766cb82503c54efed5a6df8bbf804f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/pdu_fec_decode.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_fec_decode_pydoc.h>

void bind_pdu_fec_decode(py::module& m)
{

    using pdu_fec_decode = ::gr::wisun::pdu_fec_decode;


    py::class_<pdu_fec_decode, gr::block, gr::basic_block, std::shared_ptr<pdu_fec_decode>>(
        m, "pdu_fec_decode", D(pdu_fec_decode))

        .def(py::init(&pdu_fec_decode::make),
             py::arg("drop_invalid_frames") = false,
             D(pdu_fec_decode, make))


        ;
}
