/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(power_squelch_relative_cc.h) */
/* BINDTOOL_HEADER_FILE_HASH(9de37e6bd4d7f47ff2a72f37a1725201)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/power_squelch_relative_cc.h>
// pydoc.h is automatically generated in the build directory
#include <power_squelch_relative_cc_pydoc.h>

void bind_power_squelch_relative_cc(py::module& m)
{

    using power_squelch_relative_cc = ::gr::wisun::power_squelch_relative_cc;


    py::class_<power_squelch_relative_cc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<power_squelch_relative_cc>>(
        m, "power_squelch_relative_cc", D(power_squelch_relative_cc))

        .def(py::init(&power_squelch_relative_cc::make),
             py::arg("relative_threshold"),
             py::arg("alpha") = 1.0E-4,
             D(power_squelch_relative_cc, make))


        ;
}
