/*
 * SPDX-FileCopyrightText: Copyright 2026 Free Software Foundation, Inc.
 * SPDX-FileCopyrightText: 2026 GARDENA GmbH
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_based_dc_correction_ff.h) */
/* BINDTOOL_HEADER_FILE_HASH(a5440e9a3faf777c6223c9dd71a7a779)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wisun/tag_based_dc_correction_ff.h>
// pydoc.h is automatically generated in the build directory
#include <tag_based_dc_correction_ff_pydoc.h>

void bind_tag_based_dc_correction_ff(py::module& m)
{

    using tag_based_dc_correction_ff = ::gr::wisun::tag_based_dc_correction_ff;


    py::class_<tag_based_dc_correction_ff,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tag_based_dc_correction_ff>>(
        m, "tag_based_dc_correction_ff", D(tag_based_dc_correction_ff))

        .def(py::init(&tag_based_dc_correction_ff::make),
             py::arg("signal_start_tag"),
             py::arg("signal_end_tag"),
             py::arg("estimation_length"),
             D(tag_based_dc_correction_ff, make))


        ;
}
