#!/usr/bin/env python3
#
# Copyright (c) 2026 Gardena GmbH
# SPDX-License-Identifier: GPL-3.0-or-later

"""Sniffer application to receive a single Wi-SUN channel for packet analysis with Wireshark."""

import sys
from argparse import ArgumentDefaultsHelpFormatter, ArgumentParser
from collections import OrderedDict

import osmosdr
from gnuradio import blocks, gr, pdu, wisun
from gnuradio.wisun.cli import (
    add_channel_mask_argument,
    add_list_arguments,
    add_mode_arguments,
    add_receiver_arguments,
    build_configuration,
    ensure_fifo,
    handle_list_arguments,
    run_until_interrupted,
)
from gnuradio.wisun.parameters import (
    SUN_FSK_CHANNEL_PAGE,
    WISUN_FREQUENCY_BAND_802154_MAPPING,
)
from gnuradio.wisun.util import tabular_pretty_print

RX_OFFSET_HZ = 300000


class GrWisunSingleChannelSniffer(gr.top_block):
    """Single channel sniffer main class."""

    def __init__(self, device_string, gain, dest_file, wisun_config):
        """Build the flow graph for the given configuration."""
        gr.top_block.__init__(self)
        radio_config = wisun_config.radio_configuration()

        ##################################################
        # Variables
        ##################################################
        sample_rate = 2400000
        channel_frequency = radio_config.channel_frequency(radio_config.channels[0])
        if radio_config.symbol_rate <= 100000:
            decimation = 4
        elif radio_config.symbol_rate <= 200000:
            decimation = 2
        else:
            decimation = 1
        samples_per_symbol = sample_rate / decimation / radio_config.symbol_rate
        if samples_per_symbol != int(samples_per_symbol):
            sys.stderr.write(f"ERROR: samples per symbol is not an integer: {samples_per_symbol}\n")
            sys.exit(1)
        samples_per_symbol = int(samples_per_symbol)
        print("Receiver configuration:")
        tabular_pretty_print(OrderedDict([
            ("Sample rate", f"{sample_rate / 1e6:.1f} MHz"),
            ("Frequency", f"{channel_frequency / 1e6:.1f} MHz"),
            ("Decimation", f"{decimation}"),
            ("Samples per symbol", f"{samples_per_symbol}"),
            ("Gain", f"{gain}"),
        ]))

        metadata = {
            "packet-bit-rate": radio_config.data_rate(),
            "packet-channel-page": SUN_FSK_CHANNEL_PAGE,
            "packet-channel-number": radio_config.channels[0],
            "packet-phy-band": WISUN_FREQUENCY_BAND_802154_MAPPING[wisun_config.channel_plan_id],
        }
        if radio_config.is_valid_802154_phy_mode():
            phy_type, phy_mode = radio_config.get_802154_phy_type_mode()
            metadata['packet-phy-type'] = phy_type
            metadata['packet-phy-mode'] = phy_mode

        ##################################################
        # Blocks
        ##################################################
        if device_string is None:
            osmosdr_source = osmosdr.source()
        else:
            osmosdr_source = osmosdr.source(device_string)
        osmosdr_source.set_sample_rate(sample_rate)
        osmosdr_source.set_center_freq(channel_frequency - RX_OFFSET_HZ, 0)
        osmosdr_source.set_gain_mode(False, 0)
        osmosdr_source.set_gain(gain, 0)
        osmosdr_source.set_if_gain(0, 0)
        osmosdr_source.set_bb_gain(0, 0)
        osmosdr_source.set_bandwidth(0, 0)
        single_channel_receiver = wisun.single_channel_receiver(sample_rate,
                                                                frequency_offset=RX_OFFSET_HZ,
                                                                channel_spacing=radio_config.channel_spacing,
                                                                decimation=decimation,
                                                                samples_per_symbol=samples_per_symbol,
                                                                fec=wisun_config.uses_fec(),
                                                                gated_power_squelch=False,
                                                                metadata=metadata)
        add_pcap_hdr = wisun.pdu_add_pcapng_header(True, True, True)
        pdu_to_tagged_stream = pdu.pdu_to_tagged_stream(gr.types.byte_t, 'packet_len')
        file_sink = blocks.file_sink(gr.sizeof_char*1, dest_file, False)
        file_sink.set_unbuffered(True)

        ##################################################
        # Connections
        ##################################################
        self.connect((osmosdr_source, 0), (single_channel_receiver, 0))
        self.msg_connect((single_channel_receiver, 'pdus'), (add_pcap_hdr, 'pdus'))
        self.msg_connect((add_pcap_hdr, 'pdus'), (pdu_to_tagged_stream, 'pdus'))
        self.connect((pdu_to_tagged_stream, 0), (file_sink, 0))


def main():
    """Parse the command line and run the sniffer."""
    parser = ArgumentParser(description="Single channel Wi-SUN sniffer.",
                            formatter_class=ArgumentDefaultsHelpFormatter)
    add_receiver_arguments(parser)
    add_mode_arguments(parser)
    add_channel_mask_argument(parser)
    parser.add_argument('-c', '--channel', type=int, default=0, help="Wi-SUN channel to receive")
    add_list_arguments(parser)
    args = parser.parse_args()

    handle_list_arguments(args)
    ensure_fifo(args.dest_file)

    config = build_configuration(regulatory_domain=args.regulatory_domain,
                                 channel_plan_id=args.channel_plan,
                                 phy_mode_id=(args.phy_type << 4) + args.phy_mode,
                                 allowed_channels=[args.channel],
                                 mask_channels_only=args.mask_channels_only)

    run_until_interrupted(GrWisunSingleChannelSniffer(args.device, args.gain, args.dest_file, config))


if __name__ == '__main__':
    main()
