#!/usr/bin/env python3
#
# Copyright (c) 2026 Gardena GmbH
# SPDX-License-Identifier: GPL-3.0-or-later

"""Sniffer application to receive a multiple Wi-SUN channels for packet analysis with Wireshark."""

from argparse import ArgumentDefaultsHelpFormatter, ArgumentParser

from gnuradio.wisun.cli import (
    add_channel_mask_argument,
    add_list_arguments,
    add_mode_arguments,
    add_oversampling_argument,
    add_receiver_arguments,
    build_configuration,
    ensure_fifo,
    handle_list_arguments,
    run_until_interrupted,
)
from gnuradio.wisun.multi_channel_sniffer import MultiChannelSniffer


def parse_channels(text):
    """Parse a comma-separated channel list; an empty one means every channel."""
    return [] if len(text) == 0 else [int(channel) for channel in text.split(',')]


def main():
    """Parse the command line and run the sniffer."""
    parser = ArgumentParser(description="Multi channel Wi-SUN sniffer.",
                            formatter_class=ArgumentDefaultsHelpFormatter)
    add_receiver_arguments(parser)
    add_mode_arguments(parser)
    add_channel_mask_argument(parser)
    add_oversampling_argument(parser)
    parser.add_argument('-c', '--channels', type=str, default="",
                        help="Wi-SUN channels to receive; empty: all channels")
    add_list_arguments(parser)
    args = parser.parse_args()

    handle_list_arguments(args)
    ensure_fifo(args.dest_file)

    config = build_configuration(regulatory_domain=args.regulatory_domain,
                                 channel_plan_id=args.channel_plan,
                                 phy_mode_id=(args.phy_type << 4) + args.phy_mode,
                                 allowed_channels=parse_channels(args.channels),
                                 mask_channels_only=args.mask_channels_only)

    run_until_interrupted(MultiChannelSniffer(args.device, args.gain, args.dest_file, config,
                                             oversampling=args.oversampling))


if __name__ == '__main__':
    main()
